<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Machine;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MachineTableSeeder extends Seeder
{
    public function run()
    {
        $machines = [
            [
                'name' => 'machine name',
                'machine_code_id' => '1',
                'machine_model' => '1960',
                'manfacturer' => 'Marlin Gerin',
                'user_id' => 10,
                'location_id' => 8,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC123',
                'department_id' => 1,
                'supplier' => 'china',
                'category_id' => 1,
                'notes_to_technection' => 'Ensure that all enclosure panels,doors, and structures are well maintained',
                'description' => 'Ensure that all enclosure panels,doors, and structures are well maintained',
                'criticality_id' => 1,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '2',
                'machine_model' => '1961',
                'manfacturer' => 'Marlin Gerin',
                'user_id' => 9,
                'notes_to_technection' => 'Enclosures are to be vacuum cleaned of all loose dirt and debris',
                'description' => 'Enclosures are to be vacuum cleaned of all loose dirt and debris',
                'location_id' => 3,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC124',
                'department_id' => 1,
                'supplier' => 'spain',
                'category_id' => 1,
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '3',
                'machine_model' => '1962',
                'manfacturer' => 'Schnieder electric',
                'user_id' => 8,
                'notes_to_technection' => 'All vents and fan grills are to be cleaned of all dust and/or dirt accumulations and openings are not obstructed',
                'location_id' => 1,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC125',
                'department_id' => 2,
                'supplier' => 'france',
                'category_id' => 2,
                'description' => 'All vents and fan grills are to be cleaned of all dust and/or dirt accumulations and openings are not obstructed',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '4',
                'machine_model' => '1963',
                'manfacturer' => 'Schnieder electric',
                'user_id' => 6,
                'notes_to_technection' => 'Inspect insulators and conductor supports for signs of cracking, broken pieces, and other physical damage or deterioration.',
                'location_id' => 3,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC126',
                'department_id' => 1,
                'supplier' => 'egypt',
                'category_id' => 1,
                'description' => 'Inspect insulators and conductor supports for signs of cracking, broken pieces, and other physical damage or deterioration.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '5',
                'machine_model' => '1964',
                'manufacturer' => 'Schnieder electric',
                'user_id' => 2,
                'description' => 'Repair or replace damaged insulators and supports as necessary.',
                'location_id' => 7,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC127',
                'department_id' => 1,
                'supplier' => 'canada',
                'category_id' => 1,
                'notes_to_technection' => 'Repair or replace damaged insulators and supports as necessary.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '6',
                'machine_model' => '1965',
                'manufacturer' => 'Schnieder electric',
                'user_id' => 1,
                'location_id' => 1,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC128',
                'department_id' => 2,
                'supplier' => 'italy',
                'category_id' => 2,
                'notes_to_technection' => 'Examine all bolts and connecting devices for signs of deterioration,corrosion, or overheating.',
                'description' => 'Examine all bolts and connecting devices for signs of deterioration,corrosion, or overheating.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '7',
                'machine_model' => '1966',
                'manfacturer' => 'Schnieder electric',
                'user_id' => 4,
                'location_id' => 3,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC129',
                'department_id' => 1,
                'supplier' => 'china',
                'category_id' => 1,
                'notes_to_technection' => 'Ensure that bolts and connecting devices are tight but be careful not to overtorque bolts and connecting devices since insulators are easy to damage and difficult to replace.',
                'description' => 'Ensure that bolts and connecting devices are tight but be careful not to overtorque bolts and connecting devices since insulators are easy to damage and difficult to replace.',
                'criticality_id' => 1,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '8',
                'machine_model' => '1967',
                'manfacturer' => 'Schnieder electric',
                'user_id' => 13,
                'location_id' => 8,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC130',
                'department_id' => 2,
                'supplier' => 'spain',
                'category_id' => 2,
                'notes_to_technection' => 'Examine all connections for signs of overheating, cracked or broken connectors, and signs of tracking or arcing.',
                'description' => 'Examine all connections for signs of overheating, cracked or broken connectors, and signs of tracking or arcing.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '9',
                'machine_model' => '1968',
                'manfacturer' => 'Schnieder electric',
                'user_id' => 5,
                'description' => '7',
                'location_id' => 1,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC131',
                'department_id' => 1,
                'supplier' => 'france',
                'category_id' => 1,
                'description' => 'Ensure that conductors are clean and dry.',
                'notes_to_technection' => 'Ensure that conductors are clean and dry.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '10',
                'machine_model' => '1969',
                'manfacturer' => 'FCT DI FAVEROL',
                'user_id' => 1,
                'location_id' => 3,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC132',
                'department_id' => 1,
                'supplier' => 'egypt',
                'category_id' => 1,
                'notes_to_technection' => 'Clean every component inside the machine from dust such as limit switch, sensors, selectors, proportional valve, rosetta motor…etc.',
                'description' => 'Clean every component inside the machine from dust such as limit switch, sensors, selectors, proportional valve, rosetta motor…etc.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '11',
                'machine_model' => '1970',
                'manfacturer' => 'FCT DI FAVEROL',
                'user_id' => 12,
                'description' => '5',
                'location_id' => 7,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC133',
                'department_id' => 1,
                'supplier' => 'canada',
                'category_id' => 1,
                'notes_to_technection' => 'Test every component such as conductor, overload, fuse, limit switch, sensor...etc.',
                'description' => 'Test every component such as conductor, overload, fuse, limit switch, sensor...etc.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '12',
                'machine_model' => '1971',
                'manfacturer' => 'FCT DI FAVEROL',
                'user_id' => 2,
                'location_id' => 1,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC134',
                'department_id' => 2,
                'supplier' => 'italy',
                'category_id' => 2,
                'notes_to_technection' => 'Ensure that all enclosure panels, doors, and structures are well maintained.',
                'description' => 'Ensure that all enclosure panels, doors, and structures are well maintained.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '13',
                'machine_model' => '1968',
                'manfacturer' => 'Schnieder electric',
                'user_id' => 5,
                'description' => 'Ensure that conductors are clean and dry.',
                'location_id' => 1,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC131',
                'department_id' => 1,
                'supplier' => 'france',
                'category_id' => 1,
                'notes_to_technection' => 'Ensure that conductors are clean and dry.',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '14',
                'machine_model' => '1969',
                'manfacturer' => 'FCT DI FAVEROL',
                'user_id' => 1,
                'description' => 'Clean every component inside the machine from dust such as limit switch, sensors, selectors, proportional valve, rosetta motor…etc',
                'location_id' => 3,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC132',
                'department_id' => 2,
                'supplier' => 'egypt',
                'category_id' => 2,
                'notes_to_technection' => 'Clean every component inside the machine from dust such as limit switch, sensors, selectors, proportional valve, rosetta motor…etc',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '15',
                'machine_model' => '1970',
                'manfacturer' => 'FCT DI FAVEROL',
                'user_id' => 12,
                'description' => 'Test every component such as conductor, overload, fuse, limit switch, sensor ...etc',
                'location_id' => 7,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC133',
                'department_id' => 2,
                'supplier' => 'canada',
                'category_id' => 2,
                'notes_to_technection' => 'Test every component such as conductor, overload, fuse, limit switch, sensor ...etc',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'name' => 'machine name',
                'machine_code_id' => '16',
                'machine_model' => '1971',
                'manfacturer' => 'FCT DI FAVEROL',
                'user_id' => 2,
                'description' => 'Ensure that all enclosure panels, doors, and structures are well maintained',
                'location_id' => 1,
                'contractor' => 'factory manager',
                'serial_number' => 'ABC134',
                'department_id' => 1,
                'supplier' => 'italy',
                'category_id' => 1,
                'notes_to_technection' => 'Ensure that all enclosure panels, doors, and structures are well maintained',
                'criticality_id' => 2,
                'contract_expiry_date' => Carbon::now()->addYear(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
        ];
        DB::table('machines')->insert($machines);

    }
}
