<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserTableSeeder extends Seeder
{
    public function run()
    {
        $user = [
            [
                'name' => 'Jhon',
                'address' => 'AA-12-A1',
                'phone_no' => '1234567891',
                'house_no' => '11',
                'role_id' => '4',
                'location_id' => '5',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Jhon@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mark',
                'address' => 'AA-12-A2',
                'phone_no' => '1234567891',
                'house_no' => '12',
                'role_id' => '2',
                'location_id' => '9',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Mark@gmail.com',
                'department_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Roqaia',
                'address' => 'AA-12-A3',
                'phone_no' => '1234567891',
                'house_no' => '13',
                'role_id' => '1',
                'location_id' => '3',
                'hourly_salery' => '900',
                'password' => Hash::make('12345678'),
                'email' => 'Roqaia@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sony',
                'address' => 'AA-12-A4',
                'phone_no' => '1234567891',
                'house_no' => '14',
                'role_id' => '4',
                'location_id' => '4',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Sony@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sonia',
                'address' => 'AA-12-A5',
                'phone_no' => '12345678910',
                'house_no' => '15',
                'role_id' => '3',
                'location_id' => '5',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Sonia@gmail.com',
                'department_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Abdalla',
                'address' => 'AA-12-A6',
                'phone_no' => '12345678910',
                'house_no' => '16',
                'role_id' => '1',
                'location_id' => '4',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Abdalla@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Basioni',
                'address' => 'AA-12-A7',
                'phone_no' => '12345678910',
                'house_no' => '17',
                'role_id' => '2',
                'location_id' => '1',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Basioni@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'David',
                'address' => 'AA-12-A8',
                'phone_no' => '12345678910',
                'house_no' => '18',
                'role_id' => '3',
                'location_id' => '7',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'David@gmail.com',
                'department_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mohaned',
                'address' => 'AA-12-A9',
                'phone_no' => '12345678910',
                'house_no' => '19',
                'role_id' => '4',
                'location_id' => '8',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Mohaned@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ahmed',
                'address' => 'AA-12-A10',
                'phone_no' => '12345678910',
                'house_no' => '20',
                'role_id' => '5',
                'location_id' => '1',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Ahmed@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Joo',
                'address' => 'AA-12-A11',
                'phone_no' => '12345678910',
                'house_no' => '21',
                'role_id' => '1',
                'location_id' => '2',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Joo@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mohamed',
                'address' => 'AA-12-A12',
                'phone_no' => '12345678910',
                'house_no' => '22',
                'role_id' => '2',
                'location_id' => '3',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Mohamed@gmail.com',
                'department_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Goerge',
                'address' => 'AA-12-A13',
                'phone_no' => '12345678910',
                'house_no' => '23',
                'role_id' => '3',
                'location_id' => '4',
                'hourly_salery' => '500',
                'password' => Hash::make('12345678'),
                'email' => 'Goerge@gmail.com',
                'department_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('users')->insert($user);
    }
}
