<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\WorkOrder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WorkOrderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'problem_description' => 'Fix Fused lights along the Main Corridor',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 3,
                'machine_id' => 2,
                'requster_id' => 3,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Water Pump',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 2,
                'machine_id' => 4,
                'requster_id' => 9,
                'work_priority_id' => 1,
                'received_date' => Carbon::parse('25-Jul-13'),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 2,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 2,
                'requster_id' => 1,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 3,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 1,
                'requster_id' => 6,
                'work_priority_id' => 1,
                'received_date' =>Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'problem_description' => 'Water Pump',
                'work_status_id' => 1,
                'work_type_id' => 2,
                'work_trade_id' => 1,
                'machine_id' => 6,
                'requster_id' => 4,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'problem_description' => 'Water Pump',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 2,
                'machine_id' => 4,
                'requster_id' => 9,
                'work_priority_id' => 1,
                'received_date' => Carbon::parse('25-Jul-13'),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'problem_description' => 'Clean Unit',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 3,
                'requster_id' => 6,
                'work_priority_id' => 2,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 2,
                'requster_id' => 6,
                'work_priority_id' => 1,
                'received_date' => Carbon::parse('25-Jul-13'),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'problem_description' => 'Water Pump',
                'work_status_id' => 2,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 3,
                'requster_id' => 4,
                'work_priority_id' => 1,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Water Pump',
                'work_status_id' => 1,
                'work_type_id' => 3,
                'work_trade_id' => 1,
                'machine_id' => 5,
                'requster_id' => 7,
                'work_priority_id' => 3,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 2,
                'machine_id' => 1,
                'requster_id' => 4,
                'work_priority_id' => 1,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Clean Unit',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 3,
                'requster_id' => 6,
                'work_priority_id' => 2,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 2,
                'work_trade_id' => 1,
                'machine_id' => 15,
                'requster_id' => 9,
                'work_priority_id' => 1,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 3,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 1,
                'requster_id' => 11,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 2,
                'work_trade_id' => 1,
                'machine_id' => 8,
                'requster_id' => 3,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 16,
                'requster_id' => 6,
                'work_priority_id' => 3,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 2,
                'work_type_id' => 2,
                'work_trade_id' => 2,
                'machine_id' => 4,
                'requster_id' => 5,
                'work_priority_id' => 2,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'problem_description' => 'Clean Unit',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 3,
                'requster_id' => 6,
                'work_priority_id' => 2,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 14,
                'requster_id' => 12,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Water Pump',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 2,
                'machine_id' => 4,
                'requster_id' => 9,
                'work_priority_id' => 1,
                'received_date' => Carbon::parse('25-Jul-13'),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 2,
                'work_type_id' => 2,
                'work_trade_id' => 2,
                'machine_id' => 2,
                'requster_id' => 1,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 6,
                'requster_id' => 2,
                'work_priority_id' => 1,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Clean Unit',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 3,
                'requster_id' => 6,
                'work_priority_id' => 2,
                'received_date' => Carbon::createFromDate(2013, 7, 25),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 1,
                'work_type_id' => 1,
                'work_trade_id' => 1,
                'machine_id' => 1,
                'requster_id' => 11,
                'work_priority_id' => 3,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'problem_description' => 'Hot Water Pressure Washer',
                'work_status_id' => 2,
                'work_type_id' => 2,
                'work_trade_id' => 2,
                'machine_id' => 16,
                'requster_id' => 10,
                'work_priority_id' => 2,
                'received_date' => Carbon::now(),
                'requirements' => null,
                'failure_cause' => null,
                'assign_to' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Add more data as needed
        ];
        DB::table('work_orders')->insert($data);
    }
}
